[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_compatibility = "version_20"
  directory = ".netlify/functions-internal"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200